In [2]:
import pandas as pd
import os
import sys
import string
import re
import numpy as np

In [4]:
train_df = pd.read_csv("/Users/javm/Desktop/Mercari-Price-Prediction-Project/sample_before_train_test")

In [7]:
train_df.set_index('train_id', inplace = True)

In [8]:
train_df

,item_condition_id,price,shipping,brand_mention_True,compund_sentiment_desc,clothing,beauty products,women's clothing,accessories,electronics,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
train_id,,,,,,,,,,,,,,,,,,,,,
1392338,2,14.0,0,0,0.6988,0.000000,0.000000,0.000000,0.039967,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1125521,3,41.0,0,1,0.7351,0.000255,0.000000,0.001837,0.034277,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
662640,2,24.0,0,1,0.5106,0.089750,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
195122,3,19.0,0,1,0.9750,0.000000,0.078874,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1319269,3,11.0,1,0,0.0000,0.000000,0.000000,0.000000,0.007231,0.034118,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51125,2,26.0,0,1,0.3041,0.000000,0.000000,0.000000,0.000000,0.120283,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11925,3,16.0,1,1,0.4753,0.000000,0.000000,0.002292,0.051751,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
875729,3,22.0,1,1,0.7351,0.000000,0.000000,0.000000,0.000000,0.033468,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1250401,1,21.0,0,1,0.0000,0.000000,0.078874,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
126816,1,31.0,0,1,0.7660,0.001583,0.000000,0.006178,0.024456,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
X = train_df.drop(columns = ['price'])
y = train_df['price']

In [ ]:
from sklearn

In [ ]:
import numpy as np
from sklearn import linear_model

X = train_df.drop(columns = ['price'])
y = train_df['price']

# Fit (train) the Logistic Regression classifier
clf = linear_model.LogisticRegression(solver='lbfgs')
fitted_model = clf.fit(X, y)

# Predict
prediction_result = clf.predict([(70,180)])